# Import Library

In [ ]:
import pandas as pd
import sqlite3
from io import StringIO
import csv
from ipywidgets import Layout, widgets, Style
from datetime import datetime
from IPython.display import display, clear_output

# Membuat dan Membaca Tabel

In [ ]:
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Mengaktifkan dukungan foreign key
c.execute('PRAGMA foreign_keys = ON')

c.execute('''CREATE TABLE Nasabah (
             ID_Nasabah CHAR(4) PRIMARY KEY NOT NULL,
             Nama_Nasabah TEXT,
             NoTelp_Nasabah CHAR,
             Alamat_Nasabah CHAR,
             TTL_Nasabah CHAR(10))''')

c.execute('''CREATE TABLE Rekening_Bank (
             No_Rekening INTEGER PRIMARY KEY NOT NULL,
             Pin INTEGER NOT NULL,
             ID_Nasabah CHAR(4) NOT NULL,
             ID_Akun CHAR(4) NOT NULL)''')

c.execute('''CREATE TABLE Akun_MBanking (
             ID_Akun CHAR(4) PRIMARY KEY NOT NULL,
             Username CHAR(10),
             Password CHAR(6))''')

c.execute('''CREATE TABLE Transaksi (
             ID_Transaksi CHAR(4) PRIMARY KEY NOT NULL,
             ID_Akun CHAR(4) NOT NULL,
             ID_Jenis_Transaksi CHAR(2) NOT NULL,
             Tanggal_Transaksi CHAR(10) NOT NULL,
             Nominal_Transaksi INTEGER,
             ID_Biaya_Admin CHAR(2))''')

c.execute('''CREATE TABLE Biaya_Admin (
             ID_Biaya_Admin CHAR(2) PRIMARY KEY NOT NULL,
             Jenis_Biaya_Admin CHAR NOT NULL,
             Nominal_Biaya_Admin INTEGER)''')

c.execute('''CREATE TABLE Jenis_Transaksi (
             ID_Jenis_Transaksi CHAR(2) PRIMARY KEY NOT NULL,
             Jenis_Transaksi CHAR NOT NULL)''')

conn.commit()
conn.close()

OperationalError: table Nasabah already exists

In [ ]:
Akun_Mbanking = pd.read_csv("https://raw.githubusercontent.com/Fyodorrrr/Database/main/Data-Perbankan%20-%20Akun_MBanking.csv")
Biaya_Admin = pd.read_csv("https://raw.githubusercontent.com/Fyodorrrr/Database/main/Data-Perbankan%20-%20Biaya_Admin.csv")
Nasabah = pd.read_csv("https://raw.githubusercontent.com/Fyodorrrr/Database/main/Data-Perbankan%20-%20Nasabah.csv")
Jenis_Transaksi = pd.read_csv("https://raw.githubusercontent.com/Fyodorrrr/Database/main/Data-Perbankan%20-%20Jenis_Transaksi%20(1).csv")
Transaksi = pd.read_csv("https://raw.githubusercontent.com/Fyodorrrr/Database/main/Data-Perbankan%20-%20Transaksi(fix).csv")
Rekening_Bank = pd.read_csv("https://raw.githubusercontent.com/Fyodorrrr/Database/main/Data-Perbankan%20-%20Rekening_Bank.csv")

### Tabel Akun MBanking

In [ ]:
# Hubungkan ke database SQLite
MyDB = sqlite3.connect('perbankan.db')
cursor = MyDB.cursor()

# Baca file CSV
for row in Akun_Mbanking.itertuples(index=False):
  print(row)
  if len(row) == 3:
    cursor.execute("INSERT INTO Akun_MBanking (ID_Akun, Username, Password) VALUES (?, ?, ?)", tuple(row))
  else:
    print(f"Baris tidak valid (kolom tidak sesuai): {row}")

# Komit perubahan dan tutup koneksi
MyDB.commit()
MyDB.close()

## Tabel Biaya Admin

In [ ]:
# Hubungkan ke database SQLite
MyDB = sqlite3.connect('perbankan.db')
cursor = MyDB.cursor()

# Baca file CSV
for row in Biaya_Admin.itertuples(index=False):
  print(row)
  if len(row) == 3:
    cursor.execute("INSERT INTO Biaya_Admin (ID_Biaya_Admin, Jenis_Biaya_Admin, Nominal_Biaya_Admin) VALUES (?, ?, ?)", tuple(row))
  else:
      print(f"Baris tidak valid (kolom tidak sesuai): {row}")
# Komit perubahan dan tutup koneksi
MyDB.commit()
MyDB.close()

## Tabel Nasabah

In [ ]:
# Hubungkan ke database SQLite
MyDB = sqlite3.connect('perbankan.db')
cursor = MyDB.cursor()

# Baca file CSV
for row in Nasabah.itertuples(index=False):
    print(row)
    if len(row) == 5:
        cursor.execute("INSERT INTO Nasabah (ID_Nasabah, Nama_Nasabah, NoTelp_Nasabah, Alamat_Nasabah, TTL_Nasabah) VALUES (?, ?, ?, ?, ?)", tuple(row))
    else:
        print(f"Baris tidak valid (kolom tidak sesuai): {row}")

# Komit perubahan dan tutup koneksi
MyDB.commit()
MyDB.close()

## Tabel Rekening Bank

In [ ]:
# Hubungkan ke database SQLite
MyDB = sqlite3.connect('perbankan.db')
cursor = MyDB.cursor()

# Baca file CSV
for row in Rekening_Bank.itertuples(index=False):
    print(row)
    if len(row) == 4:
        cursor.execute("INSERT INTO Rekening_Bank (ID_Nasabah, No_Rekening, Pin, ID_Akun) VALUES (?, ?, ?, ?)", tuple(row))
    else:
        print(f"Baris tidak valid (kolom tidak sesuai): {row}")

# Komit perubahan dan tutup koneksi
MyDB.commit()
MyDB.close()

## Tabel Transaksi

In [ ]:
# Hubungkan ke database SQLite
MyDB = sqlite3.connect('perbankan.db')
cursor = MyDB.cursor()

# Baca file CSV
for row in Transaksi.itertuples(index=False):
    print(row)
    if len(row) == 6:
        cursor.execute("INSERT INTO Transaksi (ID_Akun, ID_Transaksi, ID_Jenis_Transaksi, Tanggal_Transaksi, Nominal_Transaksi, ID_Biaya_Admin) VALUES (?, ?, ?, ?, ?, ?)", (row[0], row[1], row[2], row[3], row[4], row[5]))
    else:
        print(f"Baris tidak valid (kolom tidak sesuai): {row}")

# Komit perubahan dan tutup koneksi
MyDB.commit()
MyDB.close()

## Tabel Jenis Transaksi

In [ ]:
# Hubungkan ke database SQLite
MyDB = sqlite3.connect('perbankan.db')
cursor = MyDB.cursor()

# Baca file CSV
for row in Jenis_Transaksi.itertuples(index=False):
    print(row)
    if len(row) == 2:
        cursor.execute("INSERT INTO Jenis_Transaksi (ID_Jenis_Transaksi, Jenis_Transaksi) VALUES (?, ?)", (row[0], row[1]))
    else:
        print(f"Baris tidak valid (kolom tidak sesuai): {row}")

# Komit perubahan dan tutup koneksi
MyDB.commit()
MyDB.close()

# Implementasi SQL

##Insert Data

In [ ]:
# Hubungkan ke database SQLite
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Data yang akan dimasukkan
data = {
    'ID_Nasabah': 'N009',
    'Nama_Nasabah': 'Lorem Ipsum',
    'NoTelp_Nasabah': '08123456789',
    'Alamat_Nasabah': 'Jalan Mawar, Jakarta Utara',
    'TTL_Nasabah': '31-12-1995'
}

# Membuat query INSERT
columns = ', '.join(data.keys())
placeholders = ', '.join('?' for _ in data)
sql = f"INSERT INTO Nasabah ({columns}) VALUES ({placeholders})"
values = tuple(data.values())

# Menjalankan query INSERT
c.execute(sql, values)
conn.commit()
print("Data berhasil dimasukkan.")

# Menutup koneksi
conn.close()

In [ ]:
# Hubungkan ke database SQLite
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Menjalankan query untuk mengambil semua data dari tabel Nasabah
c.execute('SELECT * FROM Nasabah')

# Mengambil semua baris hasil query
rows = c.fetchall()

# Menampilkan hasil query
print("Data dalam tabel Nasabah:")
for row in rows:
    print(row)

# Menutup koneksi
conn.close()

## Update Data

In [ ]:
# Hubungkan ke database SQLite
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Data yang akan diperbarui
data = {
    'Nama_Nasabah': 'Joshua Hong',
    'NoTelp_Nasabah': '08198765432'
}
condition = "ID_Nasabah = 'N009'"

# Membuat query UPDATE
set_clause = ', '.join(f"{col} = ?" for col in data.keys())
sql = f"UPDATE Nasabah SET {set_clause} WHERE {condition}"
values = tuple(data.values())

# Menjalankan query UPDATE
c.execute(sql, values)
conn.commit()
print("Data berhasil diperbarui.")

# Menutup koneksi
conn.close()

In [ ]:
# Hubungkan ke database SQLite
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Menjalankan query untuk mengambil semua data dari tabel Nasabah
c.execute('SELECT * FROM Nasabah')

# Mengambil semua baris hasil query
rows = c.fetchall()

# Menampilkan hasil query
print("Data dalam tabel Nasabah:")
for row in rows:
    print(row)

# Menutup koneksi
conn.close()

## Implementasi Select

In [ ]:
# Membuat koneksi ke database
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Menjalankan query untuk menemukan transaksi dengan jenis transaksi 'T1'
query = '''
SELECT Transaksi.ID_Transaksi, Transaksi.Tanggal_Transaksi, Transaksi.Nominal_Transaksi, Jenis_Transaksi.Jenis_Transaksi
FROM Transaksi
JOIN Jenis_Transaksi ON Transaksi.ID_Jenis_Transaksi = Jenis_Transaksi.ID_Jenis_Transaksi
WHERE Jenis_Transaksi.ID_Jenis_Transaksi = 'T0'
'''

# Membaca hasil query ke dalam DataFrame
dfs1 = pd.read_sql_query(query, conn)

# Menutup koneksi
conn.close()

# Menampilkan DataFrame sebagai tabel
print("Data dengan Jenis Transaksi T0:")
dfs1

Data dengan Jenis Transaksi T0:

   ID_Transaksi Tanggal_Transaksi  Nominal_Transaksi Jenis_Transaksi
0             6        27-01-2022            1000000           Debit
1             7        03-02-2022              50000           Debit
2            14        05-03-2022            2000000           Debit
3            18        25-03-2022            1000000           Debit
4            26        14-04-2022            1000000           Debit
5            29        27-04-2022            2000000           Debit
6            31        03-01-2023              50000           Debit
7            40        12-04-2023            1000000           Debit
8            41        19-04-2023            2000000           Debit
9            44        18-05-2023            1000000           Debit
10           48        11-06-2023            1000000           Debit
11           56        09-09-2023            2000000           Debit
12           62        05-11-2023              50000           Debit
13           71        10-02-2024            1000000           Debit
14           72        25-02-2024            2000000           Debit
15           75        27-03-2024            1000000           Debit
16           78        29-04-2024            1000000           Debit
17           81        09-06-2024              10000           Debit

In [ ]:
# Membuat koneksi ke database
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Menjalankan query untuk menemukan nasabah dengan nama 'Agus Santoso'
query = '''
SELECT * FROM Nasabah
WHERE Nama_Nasabah = 'Agus Santoso'
'''

# Membaca hasil query ke dalam DataFrame
dfs2 = pd.read_sql_query(query, conn)

# Menutup koneksi
conn.close()
dfs2

,ID_Nasabah,Nama_Nasabah,NoTelp_Nasabah,Alamat_Nasabah,TTL_Nasabah
0,N001,Agus Santoso,81389765432,"Jalan Srengseng Sawah, Jakarta Selatan",27-10-1998

In [ ]:
# Membuat koneksi ke database
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Menjalankan query untuk memilih semua nasabah dan mengurutkan berdasarkan TTL_Nasabah
query = '''
SELECT * FROM Nasabah
ORDER BY substr(TTL_Nasabah, 7, 4)
'''

# Membaca hasil query ke dalam DataFrame
dfs3 = pd.read_sql_query(query, conn)

# Menutup koneksi
conn.close()

# Menampilkan DataFrame sebagai tabel
print("Nasabah yang diurutkan berdasarkan tahun lahir")
dfs3

Nasabah yang diurutkan berdasarkan tahun lahir

,ID_Nasabah,Nama_Nasabah,NoTelp_Nasabah,Alamat_Nasabah,TTL_Nasabah
0,N002,Budi Hartono,81234567890,"Jalan Sudirman, Jakarta Pusat",15-06-1985
1,N005,Muhammad Ilham,81789012345,"Jalan Kalimalang, Jakarta Timur",18-12-1986
2,N004,Ivan Syahputra,82345678901,"Jalan Kemang, Jakarta Selatan",05-05-1989
3,N003,Citra Dewi,81298765432,"Jalan Kebon Jeruk, Jakarta Barat",23-12-1990
4,N008,Oka Setiawan,82567890123,"Jalan Pramuka, Jakarta Timur",25-03-1990
5,N006,Kartika Dewi,81678901234,"Jalan Senayan, Jakarta Selatan",14-02-1993
6,N009,Joshua Hong,08198765432,"Jalan Mawar, Jakarta Utara",31-12-1995
7,N007,Nia Ramadhani,81890123456,"Jalan Cikini, Jakarta Pusat",07-07-1997
8,N001,Agus Santoso,81389765432,"Jalan Srengseng Sawah, Jakarta Selatan",27-10-1998

## Implementasi Join & Select

In [ ]:
#Data dengan Nominal Transaksi diatas 150.000

import sqlite3
from tabulate import tabulate

# Hubungkan ke database SQLite
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Menjalankan query untuk mengambil/SELECT data dengan JOIN antara tabel
query = """
SELECT Nasabah.Nama_Nasabah, Rekening_Bank.ID_Akun, Nasabah.ID_Nasabah, Transaksi.ID_Transaksi, Transaksi.Nominal_Transaksi
FROM Transaksi
JOIN Rekening_Bank ON Transaksi.ID_Akun = Rekening_Bank.ID_Akun
JOIN Nasabah ON Rekening_Bank.ID_Nasabah = Nasabah.ID_Nasabah
WHERE Transaksi.Nominal_Transaksi > 150000;
"""
c.execute(query)

# Mengambil semua baris hasil query
rows = c.fetchall()

# Menampilkan hasil query dalam bentuk tabel
headers = ["Nama_Nasabah", "ID_Akun", "ID_Nasabah", "ID_Transaksi", "Nominal_Transaksi"]
print("Data dengan Nominal Transaksi diatas 150.000:")
print(tabulate(rows, headers, tablefmt="github"))

# Menutup koneksi
conn.close()

Data dengan Nominal Transaksi diatas 150.000:
| Nama_Nasabah   | ID_Akun   | ID_Nasabah   |   ID_Transaksi |   Nominal_Transaksi |
|----------------|-----------|--------------|----------------|---------------------|
| Nia Ramadhani  | A007      | N007         |             75 |             1000000 |
| Budi Hartono   | A002      | N002         |             16 |              200000 |
| Budi Hartono   | A002      | N002         |             26 |             1000000 |
| Budi Hartono   | A002      | N002         |             29 |             2000000 |
| Budi Hartono   | A002      | N002         |              4 |              300000 |
| Citra Dewi     | A003      | N003         |             23 |              300000 |
| Citra Dewi     | A003      | N003         |              6 |             1000000 |
| Ivan Syahputra | A004      | N004         |             34 |              250000 |
| Ivan Syahputra | A004      | N004         |             38 |              200000 |
| Ivan Syahputra | A004      | N004         |             39 |              500000 |
| Ivan Syahputra | A004      | N004         |             40 |             1000000 |
| Ivan Syahputra | A004      | N004         |             71 |             1000000 |
| Oka Setiawan   | A008      | N008         |             69 |              200000 |
| Oka Setiawan   | A008      | N008         |             70 |              500000 |
| Oka Setiawan   | A008      | N008         |             72 |             2000000 |
| Agus Santoso   | A001      | N001         |             10 |              250000 |
| Agus Santoso   | A001      | N001         |             14 |             2000000 |
| Agus Santoso   | A001      | N001         |             17 |              500000 |
| Agus Santoso   | A001      | N001         |             18 |             1000000 |
| Kartika Dewi   | A006      | N006         |             44 |             1000000 |
| Kartika Dewi   | A006      | N006         |             56 |             2000000 |
| Kartika Dewi   | A006      | N006         |             65 |              250000 |
| Kartika Dewi   | A006      | N006         |             79 |              300000 |
| Muhammad Ilham | A005      | N005         |             41 |             2000000 |
| Muhammad Ilham | A005      | N005         |             48 |             1000000 |
| Muhammad Ilham | A005      | N005         |             49 |              300000 |
| Muhammad Ilham | A005      | N005         |             58 |              300000 |
| Muhammad Ilham | A005      | N005         |             78 |             1000000 |

In [ ]:
#Data maksimal Transaksi Tiap Nasabah

import sqlite3
from tabulate import tabulate

# Hubungkan ke database SQLite
conn = sqlite3.connect('perbankan.db')
c = conn.cursor()

# Menjalankan query untuk mengambil data dengan max(Nominal_Transaksi) dari setiap Nama_Nasabah
query = """
WITH MaxTransaksi AS (
    SELECT Rekening_Bank.ID_Nasabah, MAX(Transaksi.Nominal_Transaksi) AS Max_Nominal_Transaksi
    FROM Transaksi
    JOIN Rekening_Bank ON Transaksi.ID_Akun = Rekening_Bank.ID_Akun
    GROUP BY Rekening_Bank.ID_Nasabah
)
SELECT Nasabah.Nama_Nasabah, Rekening_Bank.ID_Akun, Nasabah.ID_Nasabah, Transaksi.ID_Transaksi, Transaksi.Nominal_Transaksi
FROM MaxTransaksi
JOIN Rekening_Bank ON MaxTransaksi.ID_Nasabah = Rekening_Bank.ID_Nasabah
JOIN Transaksi ON Rekening_Bank.ID_Akun = Transaksi.ID_Akun AND
MaxTransaksi.Max_Nominal_Transaksi = Transaksi.Nominal_Transaksi
JOIN Nasabah ON Rekening_Bank.ID_Nasabah = Nasabah.ID_Nasabah;
"""
c.execute(query)

# Mengambil semua baris hasil query
rows = c.fetchall()

# Menampilkan hasil query dalam bentuk tabel
headers = ["Nama_Nasabah", "ID_Akun", "ID_Nasabah", "ID_Transaksi", "Nominal_Transaksi"]
print("Data maksimal Transaksi Tiap Nasabah:")
print(tabulate(rows, headers, tablefmt="github"))

# Menutup koneksi
conn.close()

Data maksimal Transaksi Tiap Nasabah:
| Nama_Nasabah   | ID_Akun   | ID_Nasabah   |   ID_Transaksi |   Nominal_Transaksi |
|----------------|-----------|--------------|----------------|---------------------|
| Agus Santoso   | A001      | N001         |             14 |             2000000 |
| Budi Hartono   | A002      | N002         |             29 |             2000000 |
| Citra Dewi     | A003      | N003         |              6 |             1000000 |
| Ivan Syahputra | A004      | N004         |             40 |             1000000 |
| Ivan Syahputra | A004      | N004         |             71 |             1000000 |
| Muhammad Ilham | A005      | N005         |             41 |             2000000 |
| Kartika Dewi   | A006      | N006         |             56 |             2000000 |
| Nia Ramadhani  | A007      | N007         |             75 |             1000000 |
| Oka Setiawan   | A008      | N008         |             72 |             2000000 |

# Implementasi GUI

## Masukkan Data Transaksi

In [ ]:
# Membuat widget input
id_transaksi_input = widgets.Text(
    value='',
    description='ID Trans:',
    disabled=False)

id_akun_input = widgets.Text(
    value='',
    description='ID Akun:',
    disabled=False)

id_jenis_transaksi_input = widgets.Dropdown(
    options=['T0', 'T1', 'T2', 'T3', 'T4'],
    value='T0',
    description='ID Jenis Trans:',
    disabled=False)

tanggal_transaksi_input = widgets.DatePicker(
    description='Tgl Trans:',
    disabled=False,
    value=datetime.now())

nominal_transaksi_input = widgets.IntText(
    value=0,
    description='Nominal:',
    disabled=False)

id_biaya_admin_input = widgets.Text(
    value='',
    description='Biaya Admin:',
    disabled=False)

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data transaksi')

def insert_data(b):
    with sqlite3.connect('perbankan.db') as conn:
        c = conn.cursor()
        # Mengaktifkan foreign key
        c.execute('PRAGMA foreign_keys = ON')
        try:
            c.execute('''INSERT INTO Transaksi (ID_Transaksi, ID_Akun, ID_Jenis_Transaksi,
                         Tanggal_Transaksi, Nominal_Transaksi, ID_Biaya_Admin)
                         VALUES (?, ?, ?, ?, ?, ?)''',
                      (id_transaksi_input.value, id_akun_input.value,
                       id_jenis_transaksi_input.value, tanggal_transaksi_input.value.
                       strftime('%d-%m-%Y'), nominal_transaksi_input.value,
                       id_biaya_admin_input.value))
            print("Data transaksi berhasil dimasukkan.")
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data)

display(id_transaksi_input, id_akun_input, id_jenis_transaksi_input, tanggal_transaksi_input,
        nominal_transaksi_input, id_biaya_admin_input, submit_button)

Text(value='', description='ID Trans:')

Text(value='', description='ID Akun:')

Dropdown(description='ID Jenis Trans:', options=('T0', 'T1', 'T2', 'T3', 'T4'), value='T0')

DatePicker(value=datetime.datetime(2024, 6, 9, 6, 52, 54, 419633), description='Tgl Trans:')

IntText(value=0, description='Nominal:')

Text(value='', description='Biaya Admin:')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

Data transaksi berhasil dimasukkan.

In [ ]:
# Melihat Tabel Transaksi Terbaru
conn = sqlite3.connect('perbankan.db')
df = pd.read_sql_query('SELECT * FROM Transaksi', conn)
conn.close()

if not df.empty:
    print("Isi Tabel Transaksi:")
    display(df)
else:
    print("Tabel Transaksi Kosong.")

Isi Tabel Transaksi:

,ID_Transaksi,ID_Akun,ID_Jenis_Transaksi,Tanggal_Transaksi,Nominal_Transaksi,ID_Biaya_Admin
0,1,A001,T3,02-01-2022,57036,B3
1,2,A002,T3,12-01-2022,26206,B3
2,3,A003,T3,15-01-2022,73956,B3
3,4,A002,T2,22-01-2022,300000,B2
4,5,A002,T1,23-01-2022,100000,B0
...,...,...,...,...,...,...
77,78,A005,T0,29-04-2024,1000000,B0
78,79,A006,T2,09-05-2024,300000,B1
79,80,A005,T2,22-05-2024,150000,B1
80,81,N009,T0,09-06-2024,10000,0
81,82,N009,T0,09-06-2024,10000,0

## Cek Mutasi Berdasarkan Tanggal

In [ ]:
# Widget untuk input username dan password
username_input = widgets.Text(
    value='',
    description='Username:',
    style={'description_width': 'initial'})

password_input = widgets.Password(
    value='',
    description='Password:',
    style={'description_width': 'initial'})

login_button = widgets.Button(
    description='Login',
    button_style='success',
    tooltip='Klik untuk login')

output_login = widgets.Output()

# Widget untuk input tanggal awal dan akhir
tanggal_awal_widget = widgets.DatePicker(
    description='Tanggal Awal:',
    style={'description_width': 'initial'},
    layout={'visibility': 'hidden'})  # Awalnya tidak terlihat

tanggal_akhir_widget = widgets.DatePicker(
    description='Tanggal Akhir:',
    style={'description_width': 'initial'},
    layout={'visibility': 'hidden'})  # Awalnya tidak terlihat

cek_mutasi_button = widgets.Button(
    description='Cek Mutasi',
    button_style='info',
    tooltip='Cek mutasi berdasarkan rentang tanggal',
    layout={'visibility': 'hidden'})  # Awalnya tidak terlihat

output_mutasi = widgets.Output()

def validasi_user(username, password):
    conn = sqlite3.connect('perbankan.db')
    c = conn.cursor()
    c.execute('SELECT COUNT(*) FROM Akun_MBanking WHERE Username = ? AND Password = ?', (username, password))
    hasil = c.fetchone()[0]
    conn.close()
    return hasil > 0

# Fungsi untuk menangani login
def login(b):
    with output_login:
        clear_output()
        username = username_input.value
        password = password_input.value

        if validasi_user(username, password):
            print("Login berhasil. Silakan pilih rentang tanggal untuk cek mutasi.")
            tanggal_awal_widget.layout.visibility = 'visible'
            tanggal_akhir_widget.layout.visibility = 'visible'
            cek_mutasi_button.layout.visibility = 'visible'
        else:
            print("Username atau Password Anda salah.")

def cek_mutasi(b):
    with output_mutasi:
        clear_output()
        username = username_input.value
        password = password_input.value
        tanggal_awal = tanggal_awal_widget.value
        tanggal_akhir = tanggal_akhir_widget.value

        if not tanggal_awal or not tanggal_akhir:
            print("Harap pilih rentang tanggal yang valid.")
            return

        conn = sqlite3.connect('perbankan.db')
        c = conn.cursor()
        c.execute('''SELECT Transaksi.ID_Transaksi,
                            Transaksi.Tanggal_Transaksi,
                            Transaksi.Nominal_Transaksi,
                            Jenis_Transaksi.Jenis_Transaksi,
                            Biaya_Admin.Nominal_Biaya_Admin
                    FROM Transaksi
                    JOIN Biaya_Admin ON Transaksi.ID_Biaya_Admin = Biaya_Admin.ID_Biaya_Admin
                    JOIN Jenis_Transaksi ON Transaksi.ID_Jenis_Transaksi = Jenis_Transaksi.ID_Jenis_Transaksi
                    WHERE Transaksi.ID_Akun = (SELECT ID_Akun FROM Akun_MBanking WHERE Username = ?)
                    AND Transaksi.Tanggal_Transaksi BETWEEN ? AND ?''',
                  (username, tanggal_awal.strftime('%d-%m-%Y'), tanggal_akhir.strftime('%d-%m-%Y')))

        mutasi = c.fetchall()
        conn.close()

        if mutasi:
            df = pd.DataFrame(mutasi, columns=['ID Transaksi', 'Tanggal Transaksi',
                                               'Nominal Transaksi', 'Jenis Transaksi', 'Biaya Admin'])
            display(df)

            # Menghitung total debit dan kredit
            total_debit = df[df['Jenis Transaksi'] == 'Debit']['Nominal Transaksi'].sum()
            total_kredit = df[df['Jenis Transaksi'] != 'Debit']['Nominal Transaksi'].sum()
            selisih = total_debit - total_kredit

            # Menampilkan total debit dan kredit
            print(f"Total Debit: {total_debit}")
            print(f"Total Kredit: {total_kredit}")
            print(f"Selisih: {selisih}")
        else:
            print("Tidak ada transaksi dalam rentang tanggal tersebut.")

login_button.on_click(login)
cek_mutasi_button.on_click(cek_mutasi)

display(username_input, password_input, login_button, output_login, tanggal_awal_widget,
        tanggal_akhir_widget, cek_mutasi_button, output_mutasi)

Text(value='', description='Username:', style=DescriptionStyle(description_width='initial'))

Password(description='Password:', style=DescriptionStyle(description_width='initial'))

Button(button_style='success', description='Login', style=ButtonStyle(), tooltip='Klik untuk login')

Output()

DatePicker(value=None, description='Tanggal Awal:', layout=Layout(visibility='hidden'), style=DescriptionStyle…

DatePicker(value=None, description='Tanggal Akhir:', layout=Layout(visibility='hidden'), style=DescriptionStyl…

Button(button_style='info', description='Cek Mutasi', layout=Layout(visibility='hidden'), style=ButtonStyle(),…

Output()

## Cek Mutasi Berdasarkan Jenis Transaksi dan Tanggal

In [ ]:
# Fungsi untuk validasi user
def validasi_user(username, password):
    conn = sqlite3.connect('perbankan.db')
    c = conn.cursor()
    c.execute('SELECT * FROM Akun_MBanking WHERE Username = ? AND Password = ?', (username, password))
    result = c.fetchone()
    conn.close()
    return result is not None

# Fungsi untuk menangani login
def login(b):
    with output_login:
        clear_output()
        username = username_input.value
        password = password_input.value

        if validasi_user(username, password):
            print("Login berhasil. Silakan pilih jenis transaksi dan rentang tanggal.")
            jenis_transaksi_dropdown.layout.visibility = 'visible'
            tanggal_awal_picker.layout.visibility = 'visible'
            tanggal_akhir_picker.layout.visibility = 'visible'
            submit_button.layout.visibility = 'visible'
        else:
            print("Username atau Password Anda salah.")

# Widget input username dan password
username_input = widgets.Text(
    value='',
    description='Username:',
    style={'description_width': 'initial'})

password_input = widgets.Password(
    value='',
    description='Password:',
    style={'description_width': 'initial'})

login_button = widgets.Button(
    description='Login',
    button_style='success',
    tooltip='Klik untuk login')

output_login = widgets.Output()

login_button.on_click(login)

display(username_input, password_input, login_button, output_login)

# Widget untuk memilih jenis transaksi dengan label deskriptif
jenis_transaksi_dropdown = widgets.Dropdown(
    options=[
        ('Debit', 'T0'),
        ('Kredit Transfer Antar Rekening', 'T1'),
        ('Kredit Transfer Antar Bank', 'T2'),
        ('Kredit Transfer Virtual Account', 'T3'),
        ('Top-Up', 'T4')
    ],
    value='T0',
    description='Jenis Transaksi:',
    style={'description_width': 'initial'},
    layout={'visibility': 'hidden'})  # Awalnya widget ini tidak terlihat

# Widget untuk memilih tanggal awal dan akhir
tanggal_awal_picker = widgets.DatePicker(
    description='Tanggal Awal:',
    style={'description_width': 'initial'},
    layout={'visibility': 'hidden'})  # Awalnya widget ini tidak terlihat

tanggal_akhir_picker = widgets.DatePicker(
    description='Tanggal Akhir:',
    style={'description_width': 'initial'},
    layout={'visibility': 'hidden'})  # Awalnya widget ini tidak terlihat

# Tombol submit
submit_button = widgets.Button(
    description='Submit',
    button_style='info',
    tooltip='Klik untuk melihat mutasi transaksi',
    layout={'visibility': 'hidden'})  # Awalnya tombol ini tidak terlihat

output_mutasi = widgets.Output()

def submit(b):
    with output_mutasi:
        clear_output()
        jenis_transaksi = jenis_transaksi_dropdown.value
        tanggal_awal = tanggal_awal_picker.value
        tanggal_akhir = tanggal_akhir_picker.value

        if not tanggal_awal or not tanggal_akhir:
            print("Harap pilih rentang tanggal yang valid.")
            return

        conn = sqlite3.connect('perbankan.db')
        c = conn.cursor()
        query = '''SELECT Transaksi.ID_Transaksi,
                          Transaksi.Tanggal_Transaksi,
                          Transaksi.Nominal_Transaksi,
                          Jenis_Transaksi.Jenis_Transaksi,
                          Biaya_Admin.Nominal_Biaya_Admin
                     FROM Transaksi
                     JOIN Biaya_Admin ON Transaksi.ID_Biaya_Admin = Biaya_Admin.ID_Biaya_Admin
                     JOIN Jenis_Transaksi ON Transaksi.ID_Jenis_Transaksi = Jenis_Transaksi.ID_Jenis_Transaksi
                     WHERE Transaksi.ID_Akun = (SELECT ID_Akun FROM Akun_MBanking WHERE Username = ?)
                     AND Transaksi.Tanggal_Transaksi BETWEEN ? AND ?
                     AND Jenis_Transaksi.ID_Jenis_Transaksi = ?'''
        params = (username_input.value, tanggal_awal.strftime('%d-%m-%Y'),
                  tanggal_akhir.strftime('%d-%m-%Y'), jenis_transaksi)
        c.execute(query, params)

        mutasi = c.fetchall()
        conn.close()

        if mutasi:
            # Membuat DataFrame dari hasil query
            df = pd.DataFrame(mutasi, columns=['ID Transaksi', 'Tanggal Transaksi'
            , 'Nominal Transaksi', 'Jenis Transaksi', 'Biaya Admin'])
            display(df)
            total_debit = 0
            total_kredit = 0

            for index, row in df.iterrows():
                jenis_mutasi = 'Debit' if row['Jenis Transaksi'] in ['Debit'] else 'Kredit'
                if jenis_mutasi == 'Debit':
                    total_debit += row['Nominal Transaksi']
                else:
                    total_kredit += row['Nominal Transaksi']
            selisih = total_debit - total_kredit

            # Menampilkan total debit dan kredit
            print(f"Total Debit: {total_debit}")
            print(f"Total Kredit: {total_kredit}")
            print(f"Selisih: {selisih}")

        else:
            print("Tidak ada transaksi dalam rentang tanggal tersebut.")

login_button.on_click(login)
submit_button.on_click(submit)

display(jenis_transaksi_dropdown, tanggal_awal_picker, tanggal_akhir_picker, submit_button, output_mutasi)

Text(value='', description='Username:', style=DescriptionStyle(description_width='initial'))

Password(description='Password:', style=DescriptionStyle(description_width='initial'))

Button(button_style='success', description='Login', style=ButtonStyle(), tooltip='Klik untuk login')

Output()

Dropdown(description='Jenis Transaksi:', layout=Layout(visibility='hidden'), options=(('Debit', 'T0'), ('Kredi…

DatePicker(value=None, description='Tanggal Awal:', layout=Layout(visibility='hidden'), style=DescriptionStyle…

DatePicker(value=None, description='Tanggal Akhir:', layout=Layout(visibility='hidden'), style=DescriptionStyl…

Button(button_style='info', description='Submit', layout=Layout(visibility='hidden'), style=ButtonStyle(), too…

Output()